
INSERT INTO USERS(FIRSTNAME, LASTNAME) VALUES ('ivan','matrosov');
INSERT INTO USERS(FIRSTNAME, LASTNAME) VALUES ('alexei','koshechkin');
INSERT INTO USERS(FIRSTNAME, LASTNAME) VALUES ('john','snow');
INSERT INTO USERS(FIRSTNAME, LASTNAME) VALUES ('ILIDAN','ILIDANOVICH');
INSERT INTO USERS(FIRSTNAME, LASTNAME) VALUES ('ORGRIM','DOOMHUMMER');

INSERT INTO ROOMS (ROOMNUMBER, TYPEROOM, BED, PRICE) VALUES (11, 'Standart', 1, 200);
INSERT INTO ROOMS (ROOMNUMBER, TYPEROOM, BED, PRICE) VALUES (12, 'Standart', 1, 200);
INSERT INTO ROOMS (ROOMNUMBER, TYPEROOM, BED, PRICE) VALUES (13, 'Standart', 1, 200);
INSERT INTO ROOMS (ROOMNUMBER, TYPEROOM, BED, PRICE) VALUES (14, 'Standart', 1, 200);
INSERT INTO ROOMS (ROOMNUMBER, TYPEROOM, BED, PRICE) VALUES (15, 'Standart', 1, 200);
INSERT INTO ROOMS (ROOMNUMBER, TYPEROOM, BED, PRICE) VALUES (16, 'Standart', 2, 250);

INSERT INTO ROOMS (ROOMNUMBER, TYPEROOM, BED, PRICE) VALUES (21, 'Royal', 2, 400);
INSERT INTO ROOMS (ROOMNUMBER, TYPEROOM, BED, PRICE) VALUES (22, 'Royal', 2, 400);
INSERT INTO ROOMS (ROOMNUMBER, TYPEROOM, BED, PRICE) VALUES (23, 'Royal', 2, 400);
INSERT INTO ROOMS (ROOMNUMBER, TYPEROOM, BED, PRICE) VALUES (24, 'Royal', 2, 400);
INSERT INTO ROOMS (ROOMNUMBER, TYPEROOM, BED, PRICE) VALUES (25, 'Royal', 2, 400);

INSERT INTO ROOMS (ROOMNUMBER, TYPEROOM, BED, PRICE) VALUES (31, 'King', 2, 1500);
INSERT INTO ROOMS (ROOMNUMBER, TYPEROOM, BED, PRICE) VALUES (31, 'King', 2, 1500);
INSERT INTO ROOMS (ROOMNUMBER, TYPEROOM, BED, PRICE) VALUES (31, 'King', 2, 1500);

INSERT INTO CHEKEDROOMS (USERID, ROOMID, CHEKDATE,CHEKOUTDATE) VALUES (1, 2, '2016-07-05','2016-08-17');
INSERT INTO CHEKEDROOMS (USERID, ROOMID, CHEKDATE,CHEKOUTDATE) VALUES (2, 7, '2016-07-01','2016-07-08');
INSERT INTO CHEKEDROOMS (USERID, ROOMID, CHEKDATE,CHEKOUTDATE) VALUES (3, 5, '2016-08-12','2016-08-25');
INSERT INTO CHEKEDROOMS (USERID, ROOMID, CHEKDATE,CHEKOUTDATE) VALUES (4, 8, '2016-07-11','2016-08-01');
INSERT INTO CHEKEDROOMS (USERID, ROOMID, CHEKDATE,CHEKOUTDATE) VALUES (5, 12, '2016-07-07','2016-07-24');

INSERT INTO HYSTORY (USERID, CHECK_ROOM_ID) VALUES (1, 2);
INSERT INTO HYSTORY (USERID, CHECK_ROOM_ID) VALUES (2, 2);
INSERT INTO HYSTORY (USERID, CHECK_ROOM_ID) VALUES (3, 3);
INSERT INTO HYSTORY (USERID, CHECK_ROOM_ID) VALUES (4, 4);
INSERT INTO HYSTORY (USERID, CHECK_ROOM_ID) VALUES (5, 5);