INSERT INTO USERS VALUES (1, 'ivan','matrosov');
INSERT INTO USERS VALUES (2, 'alexei','koshechkin');
INSERT INTO USERS VALUES (3, 'john','snow');

INSERT INTO ROOMS (OWNERID, TITLE, DESCRIPTION) VALUES ( 1, 'Kino', NULL);
INSERT INTO ROOMS (OWNERID, TITLE, DESCRIPTION) VALUES ( 1, 'Mozart', NULL);
INSERT INTO ROOMS (OWNERID, TITLE, DESCRIPTION) VALUES ( 2, 'Evanescense', NULL);
INSERT INTO ROOMS (OWNERID, TITLE, DESCRIPTION) VALUES ( 2, 'SouthPark', NULL);
INSERT INTO ROOMS (OWNERID, TITLE, DESCRIPTION) VALUES ( 2, 'Quake3', NULL);

INSERT INTO TAKENITEMS (DISKID, USERID, TAKETIME) VALUES (1, 2, '2010-07-17');
INSERT INTO TAKENITEMS (DISKID, USERID, TAKETIME) VALUES (2, 3, '2010-07-17');
INSERT INTO TAKENITEMS (DISKID, USERID, TAKETIME) VALUES (3, 1, '2010-07-17');
INSERT INTO TAKENITEMS (DISKID, USERID, TAKETIME) VALUES (4, 1, '2010-07-17');
